name: Run Posts Handler

on:
  push:
    branches:
      - main  # Adjust this branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Run the script
        run: python ./Posts/posts_handler.py

      - name: Check for changes
        id: check_changes
        run: |
          run: |
          if git diff --exit-code; then
            echo "No changes detected."
          else
            git config --global user.name "Marcel Marusiak"
            git config --global user.email "marcel.marusiak@gmail.com"
            git add .
            git commit -m "Updated posts.json by github actions"
            git push origin main
          fi
